<a href="https://colab.research.google.com/github/Gaurav3666/Email-Spam-Classifier/blob/main/Email_Spam_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
messages = pd.read_csv("/content/spam (1).csv")

In [ ]:
messages

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

Data Cleaning and Preprocessing

In [ ]:
import nltk

In [ ]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [ ]:
import re

In [ ]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
wordnet = WordNetLemmatizer()
corpus = []

In [ ]:
for i in range(0,len(messages)):
  review = re.sub("[^a-zA-z]" , " " , messages["Message"][i])
  review  = review.lower()
  review = review.split()
  review = [wordnet.lemmatize(word) for word in review if word not in set(stopwords.words("english"))]
  review = " ".join(review)
  corpus.append(review)

Creating the TF - IDF model

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=1500)
X = tfidf.fit_transform(corpus).toarray()
y = pd.get_dummies(messages['Category'])
y = y.iloc[:,1].values

Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size = 0.2)

Training the model with Naive Bayes Algorithm

In [ ]:
from sklearn.naive_bayes import MultinomialNB
email_spam = MultinomialNB()
email_spam.fit(X_train , y_train)
y_pred = email_spam.predict(X_test)

Checking the Accuracy of the model

In [ ]:
from sklearn.metrics import confusion_matrix , accuracy_score
print(accuracy_score(y_test , y_pred))
cmax = confusion_matrix(y_test , y_pred)
Confusion_matrix = pd.DataFrame(cmax)
Confusion_matrix

0.9730941704035875

     0    1
0  970    3
1   27  115